# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  build-and-test: #this is the name of jon
    docker:
      - image: cimg/openjdk:11.0 #get the docker image version
    steps: # steps you want to have in pipeline
      - checkout   # Checkout the code as the first step.
      - run:    # Use mvn clean and package as the standard maven build phase
          name: Build
          command: mvn -B -DskipTests clean package
      - run:   # Then run your tests!
          name: Test
          command: mvn test

workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    jobs:  # Inside the workflow, you define the jobs you want to run.
      - build-and-test
